version: '3.9'

services:
  backend:
    image: chat-docs-backend:latest
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    container_name: chat-docs-backend
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
    volumes:
      - .:/app
    restart: unless-stopped

  frontend:
    image: chat-docs-frontend:latest
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    container_name: chat-docs-frontend
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - backend