from pydantic import BaseModel, Field
from pathlib import Path

class Question(BaseModel):
    question: str = Field(..., description="The question to be answered")

class LLMResponse(BaseModel):
    answer: str = Field(..., description="The answer generated by the LLM")

class DatabaseUpdate(BaseModel):
    file: Path = Field(..., description="Path to the file or directory to update the database")